version: '3.7'
services:

  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:v_final
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker_network
    restart: unless-stopped

  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:v_final
    depends_on: 
      - mariadb
    networks:
      - docker_network
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:v_final
    depends_on :
      - wordpress
    networks:
      - docker_network
    ports:
      - "81:81"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: unless-stopped

networks:
  docker_network:

volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/gscarama/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/gscarama/data/wordpress
      o: bind
