version: '3.8'
services:

  mariadb:
    image: mariadb_img
    container_name: mariadb
    build: ./requirements/mariadb/
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql/
    networks:
      - inception
    env_file: .env
    init: true
    restart: unless-stopped

  wordpress:
    image: wordpress_img
    container_name: wordpress
    build: ./requirements/wordpress/
    expose:
      - "9000"
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception
    env_file: .env
    init: true
    restart: unless-stopped
    depends_on:
      - mariadb

  nginx:
    image: nginx_img
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        CERT_FOLDER: ${CERT_DIR}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${DOMAIN_NAME}
    ports:
      - '443:443'
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception
    env_file: .env
    init: true
    restart: unless-stopped
    depends_on:
      - wordpress

volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gscarama/data/mysql

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gscarama/data/wordpress

networks:
  inception:
    driver: bridge
